language: erlang
otp_release:
  - 19.0

# It would be possible to use the container-based infrastructure if
# it ran trusty. However, it doesn't and wget is too old to use for
# HTTPS to buildroot.net.
sudo: required
dist: trusty

# Install dependencies
addons:
  apt:
    packages:
    - bc
    - libssl-dev

# Cache downloaded files between builds
cache:
    directories:
      - $HOME/.nerves/cache/buildroot

env:
  - MIX_ENV=test NERVES_TARGET=rpi0 CI_SYSTEM_NAME=nerves_system_$NERVES_TARGET REPO=nerves-project/$CI_SYSTEM_NAME NERVES_SYSTEM_CACHE=none NERVES_SYSTEM_COMPILER=local NERVES_PACKAGE=`pwd`

before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v1.4.2
  - make clean
  - make
  - cd ..

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - mix compile
  - mix firmware

# Deploy the build products
before_deploy:
    - cd $NERVES_PACKAGE/.nerves/artifacts/*
    - make system
    - cd $NERVES_PACKAGE
    - $NERVES_PACKAGE/deps/nerves_system_br/scripts/ci-deploy.sh
    - mkdir ~/fw
    - cp _build/test/nerves/images/*.fw ~/fw/$TRAVIS_COMMIT.fw
deploy:
  # Deploy tagged releases to GitHub
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.tar.gz"
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.fw"
    skip_cleanup: true
    overwrite: true
    on:
      repo: $REPO
      tags: true
  - provider: s3
    access_key_id: $S3_ID
    secret_access_key: $S3_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    local_dir: artifacts
    upload-dir: test
    acl: public_read
    on:
      repo: $REPO
      all_branches: true
  - provider: s3
    access_key_id: $S3_ID
    secret_access_key: $S3_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    local_dir: fw
    upload-dir: fw
    acl: public_read
    on:
      repo: $REPO
      all_branches: true

# Display build log on failure
after_failure:
  - tail -n 1000 $NERVES_PACKAGE/build.log
